= Project-WG
Author: Chuigda<icey@icey.tech>

试图用 OpenGL 3.3 画个可爱（？大概吧）的小机器人。

Try drawing a cute (?maybe) robot with OpenGL 3.3

== ⚠️⚠️⚠️ 警告：还没完成 ⚠️⚠️⚠️
[quote]
____
基于 OpenGL Core Profile 的 0.4 版本还没完成，想要成品的可以先玩 Release 里发布的 0.3.x。

OpenGL Core Profile based 0.4 edition is still under development, use 0.3.x if you want to play.
____

== ⚠️⚠️⚠️ 警告：有彩笔 ⚠️⚠️⚠️
[quote]
____
虽然从 0.4.0 之后项目改用 OpenGL 可编程管线了，但还是写的很菜。我也不怎么懂图形学的概念，只是东拼西凑一下碰巧能把东西画出来。代码质量基本就是摆烂，各种命名都有很多临时起意加玩梗的要素。
所以这项目的代码你看了真的就只能图一乐，如果你抱着学习 OpenGL 或者图形学的想法走进这个仓库，那最好还是去找个别的项目学习。

当然，如果你真的喜欢这个项目，并且在“使用”过程中遇到了困难，欢迎来 issue 页面撕逼。

Though this project migrates to OpenGL programmable pipeline since 0.4.0, my CG programming is still too vegetable.  I don't know much about CG so these code "just happen to work". The code quality
is also very poor, with namings of tons of jokes and memes. So you may only get "Kennedy-ed" if you read these code. If you'd like to learn OpenGL or CG, better to find some other project.

Or, maybe you really like this project and had some problem while "using" it, then come to the "issue" page
____

== 许可证
* Project-WG 的代码使用 link:https://www.gnu.org/licenses/agpl-3.0.txt[AGPLv3] 授权
* 角色“WGC0310”以 link:https://creativecommons.org/licenses/by-sa/4.0/legalcode.zh-Hans[CC BY-SA 4.0] 授权

* Code of Project-WG is licensed with link:https://www.gnu.org/licenses/agpl-3.0.txt[AGPLv3]
* Character "WGC0310" is licensed with link:https://creativecommons.org/licenses/by-sa/4.0/legalcode.zh-Hans[CC BY-SA 4.0]

== 其他信息
* 机器人图标取自 link:https://www.flaticon.com/free-icons/robot[Freepik - Flaticon]
* Robot icon was taken from by link:https://www.flaticon.com/free-icons/robot[Freepik - Flaticon]
