#ifndef PROJECT_WG_VERSION_H
#define PROJECT_WG_VERSION_H

#define WG_PRODUCT_NAME "Project-WG (Mio/UPhoenix special edition)"
#define WG_PRODUCT_VERSION 0,3,1,1143
#define WG_PRODUCT_VERSION_STRING "0.3.1.1143"

#define CWGLX_FILE_VERSION 0,3,0,1143
#define CWGLX_FILE_VERSION_STRING "0.3.0.1143"

#define CWUTIL_FILE_VERSION 0,3,0,1143
#define CWUTIL_FILE_VERSION_STRING "0.3.0.1143"

#ifdef CW_WIN32_RESOURCE
#define COMPANY_NAME "7th General Design Group"
#define COPYRIGHT_INFO "Copyright (C) 2022-2023 Chuigda"
#endif // CW_WIN32_RESOURCE

#endif // PROJECT_WG_VERSION_H
